### ISSUE TITLE
Please create a public archive for https://github.com/nasa/podaacpy

### ISSUE THREAD

**Issue by lewismc** [nasa/instructions#75]
Hi @hbrown017 please create a public archive for https://github.com/nasa/podaacpy

I tried emailing [nasa-data@lists.arc.nasa.gov](mailto:nasa-data@lists.arc.nasa.gov) as per the [instructions](https://github.com/nasa/instructions#instructions) however I get a delivery error. 

Thanks for any assistance.

**Comment by hbrown017** [comment]
Hi @lewismc, I am not part of the nasa-data team nor associated with the podaacpy repository.

Mentioning @darith27 if he is able to assist.

Thanks.

**Comment by lewismc** [comment]
Apologies @hbrown017 I tagged you because you are on the [commit history for the instructions repository](https://github.com/nasa/instructions/commits/master). Sorry for the noise. I will make sure to clean this up once I can archive that repository. Thanks for tagging darith27.

**Comment by lewismc** [comment]
I’ll close this issue and take it over to the Podaacpy repository.
